version: '3'

services:
  spring:
    build: ./backend/fish-server
    expose:
      - "8080"
    volumes:
      - /home/ubuntu/images:/root/data/images
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/images:/home/ubuntu/images
  flask:
    build: ./deep_learning
    expose:
      - "5000"
