version: '3'

services:
  spring:
    build: ./backend/fish-server
    expose:
      - 8080
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/images/collection:/home/ubuntu/images/collection
